spring:
  application:
    name: lab-4-noun
server:
  port: ${PORT:${SERVER_PORT:0}}
words: “boat,book,vote,seat,backpack,partition,groundhog”
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/